apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tricky-porpoise-nodejs 
  janus-idp.io/tekton: tricky-porpoise-nodejs
  backstage.io/kubernetes-id: tricky-porpoise-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tricky-porpoise-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  